### ISSUE TITLE
怎么用管理员怎么执行cmd命令

### ISSUE THREAD

**Issue by pping** [fofolee/uTools-quickcommand#36]
想要执行这个命令
cmd /k "netsh interface set interface "10.0.80.1" disable && netsh interface set interface "10.0.80.1" enable"

**Comment by fofolee** [comment]
管理员启动 utools
或者借助 gsudo

**Comment by pping** [comment]
管理员启动 utools试了下，确实可以，谢谢
 
发件人： fofolee
发送时间： 2021-03-11 11:39
收件人： fofolee/uTools-QuickerCommand
抄送： pping; Author
主题： Re: [fofolee/uTools-QuickerCommand] 怎么用管理员怎么执行cmd命令 (#36)
管理员启动 utools
或者借助 gsudo

**Comment by wenmin92** [comment]
还可以通过 `Start-Process -Verb RunAs` 触发权限提升
