### ISSUE TITLE
如何新增分类

### ISSUE THREAD

**Issue by pping** [fofolee/uTools-quickcommand#37]
只有默认分类，完全不知道该怎么添加

**Comment by fofolee** [comment]
新建命令时加标签

**Comment by pping** [comment]
多谢指导，我添加成功了，不过如果标签下面有很多快捷命令，怎么给标签重命名呢。



 
发件人： fofolee
发送时间： 2021-03-11 11:38
收件人： fofolee/uTools-QuickerCommand
抄送： pping; Author
主题： Re: [fofolee/uTools-QuickerCommand] 如何新增分类 (#37)
新建命令时加标签

**Comment by fofolee** [comment]
> 多谢指导，我添加成功了，不过如果标签下面有很多快捷命令，怎么给标签重命名呢。 发件人： fofolee 发送时间： 2021-03-11 11:38 收件人： fofolee/uTools-QuickerCommand 抄送： pping; Author 主题： Re: [fofolee/uTools-QuickerCommand] 如何新增分类 (#37) 新建命令时加标签 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

暂时不支持标签的重命名，后续更新的话可能会加上
