### ISSUE TITLE
软件启动面板要怎么配置

### ISSUE THREAD

**Issue by muziling** [fofolee/uTools-quickcommand#38]
比如要我给 d:\qq\qq.exe 和 d:\wechat\wechat.exe两个软件配置为启动面板，应该要怎么配置？

快捷命令配置为窗口进程后没办法切换到 启动面板模式

**Comment by fofolee** [comment]
目前只支持关键字方式启动，需要把相应的命令调整为关键字启动

**Comment by muziling** [comment]
![image](https://user-images.githubusercontent.com/1459795/112242425-cdbaa680-8c86-11eb-8011-b65befc4bef7.png)
这样配了，提示快捷面板仅支持匹配模式为关键词的命令，当前标签不存在该类型命令或者该命令未启用

**Comment by fofolee** [comment]
> ![image](https://user-images.githubusercontent.com/1459795/112242425-cdbaa680-8c86-11eb-8011-b65befc4bef7.png)
> 这样配了，提示快捷面板仅支持匹配模式为关键词的命令，当前标签不存在该类型命令或者该命令未启用

目前无法复现，能录个动图吗
![](https://i.postimg.cc/15rDkf10/605b35a53bf21.gif)

**Comment by muziling** [comment]
在家里的电脑可以，估计是我一开始命令选窗口进程，保存，然后修改为关键字类型，有配置残留导致的

**Comment by muziling** [comment]
面板里的大图标，很不清晰，图标来源我是选择应用exe文件，我在windows文件管理器放大软件图标很清晰
![image](https://user-images.githubusercontent.com/1459795/112327602-8537d300-8cf0-11eb-89bd-164b21776b6a.png)

**Comment by fofolee** [comment]
> 面板里的大图标，很不清晰，图标来源我是选择应用exe文件，我在windows文件管理器放大软件图标很清晰
> ![image](https://user-images.githubusercontent.com/1459795/112327602-8537d300-8cf0-11eb-89bd-164b21776b6a.png)

我在win下测试了下确实如此，但是主要是utools的getfileico的api获取的图标分辨率就不高
