### ISSUE TITLE
更新最新版之后，之前的自定义快捷命令失效

### ISSUE THREAD

**Issue by u2019999999** [fofolee/uTools-quickcommand#40]
之前定义的命令都失效了
![image](https://user-images.githubusercontent.com/81562599/112826544-b8e37600-90bf-11eb-934c-a3179bb8cbe8.png)
![image](https://user-images.githubusercontent.com/81562599/112826254-525e5800-90bf-11eb-8bfa-cf39acdeda2a.png)

**Comment by fofolee** [comment]
收到，马上修复
