### ISSUE TITLE
快捷面板无法用

### ISSUE THREAD

**Issue by withb** [fofolee/uTools-quickcommand#45]
![image](https://user-images.githubusercontent.com/40620197/123116734-bea8e780-d473-11eb-82ec-7bd3a7633136.png)

**Comment by fofolee** [comment]
在未分类下面吧，需要给你的命令加一个标签

**Comment by withb** [comment]
谢谢，太好用了，
<img width="583" alt="图片_1" src="https://user-images.githubusercontent.com/40620197/124398518-afb21700-dd48-11eb-94d7-fa0287971650.Png">
建议直接在关键字哪里加上超链接，可以直接点击关键字进入程序，这样就可以当作快捷启动面板了。

**Comment by fofolee** [comment]
安排
