### ISSUE TITLE
您好，如何新打开一个默认浏览器，不是以tab方式

### ISSUE THREAD

**Issue by remainfox** [fofolee/uTools-quickcommand#51]
您好，如何新打开一个默认浏览器，不是以tab方式，
1、使用visit会以tab标签方式打开，不满足新打开浏览器需求
2、open命令需要指定浏览器的绝对路径，当utools云同步后，涉及跨多个电脑场景（公司和家），因为浏览器安装位置不同会open失败

**Comment by fofolee** [comment]
> 您好，如何新打开一个默认浏览器，不是以tab方式， 1、使用visit会以tab标签方式打开，不满足新打开浏览器需求 2、open命令需要指定浏览器的绝对路径，当utools云同步后，涉及跨多个电脑场景（公司和家），因为浏览器安装位置不同会open失败

特殊变量->{{usr:}} -> 新增一个变量用来存储浏览器路径 -> 勾选仅本机

**Comment by remainfox** [comment]
不太会，能否举个例子

**Comment by fofolee** [comment]
![](https://s2.loli.net/2022/06/02/BbZaMzlPLVEAedy.png)

**Comment by remainfox** [comment]
谢谢
